version: '3.9'

services:

  ubuntu:
    container_name: ${PREFIX}_ubuntu
    build: ./ubuntu
    ports:
      - "80:80"
    tty: true
    volumes:
      - ./ubuntu/entrypoint.sh:/usr/local/bin/entrypoint.sh 
      - ./ubuntu/.bashrc:/home/docker/.bashrc
      - ./www:/var/www
      - ./ubuntu/supervisor-laravel-worker.ini:/etc/supervisord.d/supervisor-laravel-worker.ini
      - ./ubuntu/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ${SSH_AUTH_SOCK}:/ssh-agent

  mariadb:
    container_name: ${PREFIX}_mariadb
    image: mariadb:lts-jammy
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=db
      - MARIADB_USER=dbuser
      - MARIADB_PASSWORD=dbpass

    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  meilisearch:
    container_name: ${PREFIX}_meilisearch
    # build: ./meilisearch
    image: getmeili/meilisearch:v1.4
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data  
    environment:
      -  MEILI_MASTER_KEY=MASTER_KEY

volumes:
  mariadb_data:
  meili_data: