FROM getmeili/meilisearch:v1.4

LABEL maintainer "Igor Talevski <igor.talevski@internetbrands.com>"

EXPOSE 7700

ARG DEBIAN_FRONTEND=noninteractive


ENTRYPOINT ["/bin/sh", "-c" , "tail -f /dev/null "]
